#!/usr/bin/env bash
set -eo pipefail

SRC="$HOME/code"
DST=rclone://drive:backup/dev/code

[[ -d "$SRC" ]]

args=(
  --verbosity info
  --encrypt-key 00828C1D
  --exclude-other-filesystems
  --exclude "$SRC/*/_mnt"
  --exclude "$SRC/ytdump/meta"
  --exclude "$SRC/ytdump/out"
)

if [[ $# = 0 ]]; then
  args+=(
    incr
    "$SRC"
    "$DST"
  )
else
  args+=("$@" "$DST")
fi

exec duplicity "${args[@]}"
